export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST";
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS";
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL";

export const BLOGS_CATEGORY_REQUEST = " BLOGS_CATEGORY_REQUEST";
export const BLOGS_CATEGORY_SUCCESS = "BLOGS_CATEGORY_SUCCESS";
export const BLOGS_CATEGORY_FAIL = "BLOGS_CATEGORY_FAIL";

export const BLOG_BY_ID_REQUEST = " BLOG_BY_ID_REQUEST";
export const BLOG_BY_ID_SUCCESS = "BLOG_BY_ID_SUCCESS";
export const BLOG_BY_ID_FAIL = "BLOG_BY_ID_FAIL";

export const USER_SIGNUP_REQUEST = " USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = " USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const CREATE_COMMENT_REQUEST = " CREATE_COMMENT_REQUEST";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";
export const CREATE_COMMENT_RESET = "CREATE_COMMENT_RESET";

export const CREATE_POST_REQUEST = " CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";
export const CREATE_POST_RESET = "CREATE_POST_RESET";

export const BLOG_DELETE_SUCCESS = "BLOG_DELETE_SUCCESS";
export const BLOG_DELETE_RESET = "BLOG_DELETE_RESET";
