export const ALL_BLOGS_REQUEST = "ALL_BLOGS_REQUEST";
export const ALL_BLOGS_SUCCESS = "ALL_BLOGS_SUCCESS";
export const ALL_BLOGS_FAIL = "ALL_BLOGS_FAIL";

export const BLOGS_CATEGORY_REQUEST = " BLOGS_CATEGORY_REQUEST";
export const BLOGS_CATEGORY_SUCCESS = "BLOGS_CATEGORY_SUCCESS";
export const BLOGS_CATEGORY_FAIL = "BLOGS_CATEGORY_FAIL";
